/*
Date: May/6/2025

Intro: In this Do-file, we build the panel dataset

Author: Oscar Andres Garnica Toro
*/


clear all 
set more off

*globals
global cd "directory" 
global data "$cd/2_data"
global output "$cd/3_output"
global tables "$output/1_tables"


*1.import dataset
*import delimited using "C:\Users\oagt_\Dropbox (Good Business Lab)\AIJS\5.data\2.raw\all_data_clean.csv", clear
import excel using "/Users/oscarandresgarnicatoro/Good Business Lab Dropbox/Oscar   Garnica/AIJS/5.data/2.raw/all_data_clean.xlsx", sheet("all_data_clean") firstrow clear

*Loop over all variables in the dataset
foreach var of varlist _all {
    // Rename each variable to its lowercase version
    rename `var' `=lower("`var'")'
}


*2.extract the day of the date variable
{
	foreach x in createdat updatedat survey_createdat f1survey_createdat f2survey_createdat f3survey_createdat psychometriccompletedat followup1completedat followup2completedat followup3completedat {
		
		gen `x'e = dofc(`x')
		format `x'e %td
}

}

*3.create variable with the number of days in trial
	{
	
	gen days_in_trial = today() - survey_createdate
	order days_in_trial, b(createdate)
	
	}

*4.Panel

*Drop SMS data for now
drop mz smsf1round1applicationsweek smsf1round1havejob smsf1round1hourlywage smsf1round1interviewsweek smsf1round1satisfaction smsf1round1sector smsf1round1stillatjob smsf1round1stillopen smsf1round2applicationsweek smsf1round2havejob smsf1round2hourlywage smsf1round2interviewsweek smsf1round2satisfaction smsf1round2sector smsf1round2stillatjob smsf1round2stillopen smsf1round3applicationsweek smsf1round3havejob smsf1round3hourlywage smsf1round3interviewsweek smsf1round3satisfaction smsf1round3sector smsf1round3stillatjob smsf1round3stillopen smsf1round4applicationsweek smsf1round4havejob smsf1round4hourlywage smsf1round4interviewsweek smsf1round4satisfaction smsf1round4sector smsf1round4stillatjob smsf1round4stillopen smsf1round5applicationsweek smsf1round5havejob smsf1round5hourlywage smsf1round5interviewsweek smsf1round5satisfaction smsf1round5sector smsf1round5stillatjob smsf1round5stillopen smsf2round1applicationsweek smsf2round1havejob smsf2round1hourlywage smsf2round1interviewsweek smsf2round1satisfaction smsf2round1sector smsf2round1stillatjob smsf2round1stillopen smsf2round2applicationsweek smsf2round2havejob smsf2round2hourlywage smsf2round2interviewsweek smsf2round2satisfaction smsf2round2sector smsf2round2stillatjob smsf2round2stillopen smsf2round3applicationsweek smsf2round3havejob smsf2round3hourlywage smsf2round3interviewsweek smsf2round3satisfaction smsf2round3sector smsf2round3stillatjob smsf2round3stillopen smsf2round4applicationsweek smsf2round4havejob smsf2round4hourlywage smsf2round4interviewsweek smsf2round4satisfaction smsf2round4sector smsf2round4stillatjob smsf2round4stillopen psychometricsround1application psychometricsround1havejob psychometricsround1hourlywage psychometricsround1interviewsw psychometricsround1satisfactio psychometricsround1sector psychometricsround1stillatjob psychometricsround1stillopen psychometricsround2application psychometricsround2havejob psychometricsround2hourlywage psychometricsround2interviewsw psychometricsround2satisfactio psychometricsround2sector psychometricsround2stillatjob psychometricsround2stillopen psychometricsround3application psychometricsround3havejob psychometricsround3hourlywage psychometricsround3interviewsw psychometricsround3satisfactio psychometricsround3sector psychometricsround3stillatjob psychometricsround3stillopen

*structure the dataset
order clicks saves apps, a(zip)
order createdate, a(createdat) 
order updatedate days_in_trial, a(updatedat)

order survey_createdat survey_createdate, a(preferredhours)
order psychometriccompletedat psychometriccompletedate , a(survey_createdate)
order f1survey_createdate, a(f1survey_createdat)
order followup1completedat followup1completedate, a(f1survey_createdate)
order f2survey_createdate, a(f2survey_createdat)
order followup2completedat followup2completedate, a(f2survey_createdate)
order f3survey_createdate, a(f3survey_createdat)
order followup3completedat followup3completedate, a(f3survey_createdate)

rename psychometriccompletedat completedat
rename psychometriccompletedate completedate
rename followup1completedat f1completedat
rename followup1completedate f1completedate
rename followup2completedat f2completedat
rename followup2completedate f2completedate
rename followup3completedat f3completedat 
rename  followup3completedate  f3completedate
 
*Let's rename the var names with the right syntax of so we can transpose the data
global bl_survey "survey_createdat survey_createdate completedat completedate wouldnever0 wouldnever1 wouldnever2 wouldnever3 wouldnever4 wouldnever5 wouldnever6 wouldnever7 wouldnever8 ranklikely_advance0 ranklikely_advance1 ranklikely_advance2 ranklikely_advance3 ranklikely_advance4 ranklikely_advance5 ranklikely_advance6 ranklikely_advance7 ranklikely_advance8 ranklikely_best0 ranklikely_best1 ranklikely_best2 ranklikely_best3 ranklikely_best4 ranklikely_best5 ranklikely_best6 ranklikely_best7 ranklikely_best8 ranklikely_fast0 ranklikely_fast1 ranklikely_fast2 ranklikely_fast3 ranklikely_fast4 ranklikely_fast5 ranklikely_fast6 ranklikely_fast7 ranklikely_fast8 jobpriorities0 jobpriorities1 jobpriorities2 wouldacceptsalesagent wouldacceptwarehouse wouldacceptwaiter wouldacceptchildcare wouldacceptreceptionist wouldaccepthealthcare wouldacceptcook wouldacceptcustomerservice wouldacceptcashier job_employment_status job_hourly_pay job_last_employed job_primary_function job_primary_functioncomment job_search_applications job_search_hours job_search_interviews job_search_offers job_searching job_start job_weekly_hours job_years_experience job_ever_fulfilled0 job_ever_fulfilled1 job_ever_fulfilled2 job_ever_fulfilled3 job_ever_fulfilled4 job_ever_fulfilled5 job_ever_fulfilled6 job_ever_fulfilled7 job_ever_fulfilled8 job_ever_fulfilled9 job_history0 job_history1 job_history2 job_history3 job_history4 job_search_sectors0 job_search_sectors1 job_search_sectors2 job_search_sectors3 job_search_sectors4 job_search_sectors5 job_search_sectors6 job_search_sectors7 job_search_sectors8 job_search_sectors9 sat_appreciated sat_coworkers sat_meaning sat_overall sat_pay"

foreach var in $bl_survey {
	rename `var' `var'_s0
}

global f1vars "f1survey_createdat f1survey_createdate f1completedat f1completedate f1wouldnever0 f1wouldnever1 f1wouldnever2 f1wouldnever3 f1wouldnever4 f1wouldnever5 f1wouldnever6 f1wouldnever7 f1wouldnever8 f1ranklikely_advance0 f1ranklikely_advance1 f1ranklikely_advance2 f1ranklikely_advance3 f1ranklikely_advance4 f1ranklikely_advance5 f1ranklikely_advance6 f1ranklikely_advance7 f1ranklikely_advance8 f1ranklikely_best0 f1ranklikely_best1 f1ranklikely_best2 f1ranklikely_best3 f1ranklikely_best4 f1ranklikely_best5 f1ranklikely_best6 f1ranklikely_best7 f1ranklikely_best8 f1ranklikely_fast0 f1ranklikely_fast1 f1ranklikely_fast2 f1ranklikely_fast3 f1ranklikely_fast4 f1ranklikely_fast5 f1ranklikely_fast6 f1ranklikely_fast7 f1ranklikely_fast8 f1jobpriorities0 f1jobpriorities1 f1jobpriorities2 f1wouldaccepthealthcare f1wouldacceptwarehouse f1wouldacceptreceptionist f1wouldacceptcashier f1wouldacceptcustomerservice f1wouldacceptsalesagent f1wouldacceptwaiter f1wouldacceptchildcare f1wouldacceptcook f1job_employment_status f1job_hourly_pay f1job_last_employed f1job_primary_function f1job_primary_functioncomment f1job_search_applications_platf f1job_search_applications f1job_search_hours f1job_search_interviews_platfor f1job_search_interviews f1job_search_length f1job_search_offers_platform f1job_search_offers f1job_searching f1job_start f1job_weekly_hours f1job_where_found f1job_where_foundcomment f1job_search_sectors0 f1job_search_sectors1 f1job_search_sectors2 f1job_search_sectors3 f1job_search_sectors4 f1job_search_sectors5 f1job_search_sectors6 f1job_search_sectors7 f1job_search_sectors8 f1job_search_sectors9 f1sat_appreciated f1sat_coworkers f1sat_meaning f1sat_overall f1sat_pay"

foreach var in $f1vars {
	local newname = substr("`var'", 3, .)
    rename `var' `newname'_s1
}


global f2vars "f2survey_createdat f2survey_createdate f2completedat f2completedate f2wouldnever0 f2wouldnever1 f2wouldnever2 f2wouldnever3 f2wouldnever4 f2wouldnever5 f2wouldnever6 f2wouldnever7 f2wouldnever8 f2ranklikely_advance0 f2ranklikely_advance1 f2ranklikely_advance2 f2ranklikely_advance3 f2ranklikely_advance4 f2ranklikely_advance5 f2ranklikely_advance6 f2ranklikely_advance7 f2ranklikely_advance8 f2ranklikely_best0 f2ranklikely_best1 f2ranklikely_best2 f2ranklikely_best3 f2ranklikely_best4 f2ranklikely_best5 f2ranklikely_best6 f2ranklikely_best7 f2ranklikely_best8 f2ranklikely_fast0 f2ranklikely_fast1 f2ranklikely_fast2 f2ranklikely_fast3 f2ranklikely_fast4 f2ranklikely_fast5 f2ranklikely_fast6 f2ranklikely_fast7 f2ranklikely_fast8 f2jobpriorities0 f2jobpriorities1 f2jobpriorities2 f2wouldacceptcustomerservice f2wouldacceptcook f2wouldacceptreceptionist f2wouldacceptwaiter f2wouldaccepthealthcare f2wouldacceptcashier f2wouldacceptchildcare f2wouldacceptwarehouse f2wouldacceptsalesagent f2job_employment_status f2job_hourly_pay f2job_last_employed f2job_primary_function f2job_primary_functioncomment f2job_search_applications_platf f2job_search_applications f2job_search_hours f2job_search_interviews_platfor f2job_search_interviews f2job_search_length f2job_search_offers_platform f2job_search_offers f2job_searching f2job_start f2job_weekly_hours f2job_where_found f2job_where_foundcomment f2job_search_sectors0 f2job_search_sectors1 f2job_search_sectors2 f2job_search_sectors3 f2job_search_sectors4 f2job_search_sectors5 f2job_search_sectors6 f2job_search_sectors7 f2job_search_sectors8 f2job_search_sectors9 f2sat_appreciated f2sat_coworkers f2sat_meaning f2sat_overall f2sat_pay"

foreach var in $f2vars {
	local newname = substr("`var'", 3, .)
    rename `var' `newname'_s2
}

global f3vars "f3survey_createdat f3survey_createdate f3completedat f3completedate f3wouldnever0 f3wouldnever1 f3wouldnever2 f3wouldnever3 f3wouldnever4 f3wouldnever5 f3wouldnever6 f3wouldnever7 f3wouldnever8 f3ranklikely_advance0 f3ranklikely_advance1 f3ranklikely_advance2 f3ranklikely_advance3 f3ranklikely_advance4 f3ranklikely_advance5 f3ranklikely_advance6 f3ranklikely_advance7 f3ranklikely_advance8 f3ranklikely_best0 f3ranklikely_best1 f3ranklikely_best2 f3ranklikely_best3 f3ranklikely_best4 f3ranklikely_best5 f3ranklikely_best6 f3ranklikely_best7 f3ranklikely_best8 f3ranklikely_fast0 f3ranklikely_fast1 f3ranklikely_fast2 f3ranklikely_fast3 f3ranklikely_fast4 f3ranklikely_fast5 f3ranklikely_fast6 f3ranklikely_fast7 f3ranklikely_fast8 f3jobpriorities0 f3jobpriorities1 f3jobpriorities2 f3wouldacceptsalesagent f3wouldaccepthealthcare f3wouldacceptcook f3wouldacceptwaiter f3wouldacceptwarehouse f3wouldacceptcustomerservice f3wouldacceptreceptionist f3wouldacceptcashier f3wouldacceptchildcare f3wouldaccept0 f3job_employment_status f3job_hourly_pay f3job_last_employed f3job_primary_function f3job_primary_functioncomment f3job_search_applications_platf f3job_search_applications f3job_search_hours f3job_search_interviews_platfor f3job_search_interviews f3job_search_length f3job_search_offers_platform f3job_search_offers f3job_searching f3job_start f3job_weekly_hours f3job_where_found f3job_where_foundcomment f3job_search_sectors0 f3job_search_sectors1 f3job_search_sectors2 f3job_search_sectors3 f3job_search_sectors4 f3job_search_sectors5 f3job_search_sectors6 f3job_search_sectors7 f3job_search_sectors8 f3job_search_sectors9 f3sat_appreciated f3sat_coworkers f3sat_meaning f3sat_overall f3sat_pay"

foreach var in $f3vars {
	local newname = substr("`var'", 3, .)
    rename `var' `newname'_s3
}

*Reshape long the datase
reshape long survey_createdat_s survey_createdate_s completedat_s completedate_s wouldnever0_s wouldnever1_s wouldnever2_s wouldnever3_s wouldnever4_s wouldnever5_s wouldnever6_s wouldnever7_s wouldnever8_s ranklikely_advance0_s ranklikely_advance1_s ranklikely_advance2_s ranklikely_advance3_s ranklikely_advance4_s ranklikely_advance5_s ranklikely_advance6_s ranklikely_advance7_s ranklikely_advance8_s ranklikely_best0_s ranklikely_best1_s ranklikely_best2_s ranklikely_best3_s ranklikely_best4_s ranklikely_best5_s ranklikely_best6_s ranklikely_best7_s ranklikely_best8_s ranklikely_fast0_s ranklikely_fast1_s ranklikely_fast2_s ranklikely_fast3_s ranklikely_fast4_s ranklikely_fast5_s ranklikely_fast6_s ranklikely_fast7_s ranklikely_fast8_s jobpriorities0_s jobpriorities1_s jobpriorities2_s wouldacceptsalesagent_s wouldacceptwarehouse_s wouldacceptwaiter_s wouldacceptchildcare_s wouldacceptreceptionist_s wouldaccepthealthcare_s wouldacceptcook_s wouldacceptcustomerservice_s wouldacceptcashier_s job_employment_status_s job_hourly_pay_s job_last_employed_s job_primary_function_s job_primary_functioncomment_s job_search_applications_s job_search_hours_s job_search_interviews_s job_search_offers_s job_searching_s job_start_s job_weekly_hours_s job_years_experience_s job_ever_fulfilled0_s job_ever_fulfilled1_s job_ever_fulfilled2_s job_ever_fulfilled3_s job_ever_fulfilled4_s job_ever_fulfilled5_s job_ever_fulfilled6_s job_ever_fulfilled7_s job_ever_fulfilled8_s job_ever_fulfilled9_s job_history0_s job_history1_s job_history2_s job_history3_s job_history4_s job_search_sectors0_s job_search_sectors1_s job_search_sectors2_s job_search_sectors3_s job_search_sectors4_s job_search_sectors5_s job_search_sectors6_s job_search_sectors7_s job_search_sectors8_s job_search_sectors9_s sat_appreciated_s sat_coworkers_s sat_meaning_s sat_overall_s sat_pay_s job_search_applications_platf_s job_search_interviews_platfor_s job_search_length_s job_search_offers_platform_s job_where_found_s job_where_foundcomment_s ///
wouldaccept0_s, ///
i(userid) j(survey)

*remove the suffix "_s"
global cleaned_vars survey_createdat_s survey_createdate_s completedat_s completedate_s wouldnever0_s wouldnever1_s wouldnever2_s wouldnever3_s wouldnever4_s wouldnever5_s wouldnever6_s wouldnever7_s wouldnever8_s ranklikely_advance0_s ranklikely_advance1_s ranklikely_advance2_s ranklikely_advance3_s ranklikely_advance4_s ranklikely_advance5_s ranklikely_advance6_s ranklikely_advance7_s ranklikely_advance8_s ranklikely_best0_s ranklikely_best1_s ranklikely_best2_s ranklikely_best3_s ranklikely_best4_s ranklikely_best5_s ranklikely_best6_s ranklikely_best7_s ranklikely_best8_s ranklikely_fast0_s ranklikely_fast1_s ranklikely_fast2_s ranklikely_fast3_s ranklikely_fast4_s ranklikely_fast5_s ranklikely_fast6_s ranklikely_fast7_s ranklikely_fast8_s jobpriorities0_s jobpriorities1_s jobpriorities2_s wouldacceptsalesagent_s wouldacceptwarehouse_s wouldacceptwaiter_s wouldacceptchildcare_s wouldacceptreceptionist_s wouldaccepthealthcare_s wouldacceptcook_s wouldacceptcustomerservice_s wouldacceptcashier_s job_employment_status_s job_hourly_pay_s job_last_employed_s job_primary_function_s job_primary_functioncomment_s job_search_applications_s job_search_hours_s job_search_interviews_s job_search_offers_s job_searching_s job_start_s job_weekly_hours_s job_years_experience_s job_ever_fulfilled0_s job_ever_fulfilled1_s job_ever_fulfilled2_s job_ever_fulfilled3_s job_ever_fulfilled4_s job_ever_fulfilled5_s job_ever_fulfilled6_s job_ever_fulfilled7_s job_ever_fulfilled8_s job_ever_fulfilled9_s job_history0_s job_history1_s job_history2_s job_history3_s job_history4_s job_search_sectors0_s job_search_sectors1_s job_search_sectors2_s job_search_sectors3_s job_search_sectors4_s job_search_sectors5_s job_search_sectors6_s job_search_sectors7_s job_search_sectors8_s job_search_sectors9_s sat_appreciated_s sat_coworkers_s sat_meaning_s sat_overall_s sat_pay_s job_search_applications_platf_s job_search_interviews_platfor_s job_search_length_s job_search_offers_platform_s job_where_found_s job_where_foundcomment_s wouldaccept0_s
	
foreach var in $cleaned_vars {
    local newname = substr("`var'", 1, length("`var'") - 2)
    rename `var' `newname'
}


*declare panel
encode userid, gen (id_num)

xtset id_num survey

*save the panel dataset	
save "$data/1b_panel_data.dta", replace
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	